# Generated by Django 5.2 on 2025-04-09 05:31

import django.db.models.deletion
import paddy_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('customer_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('GST', models.CharField(blank=True, max_length=15, null=True, validators=[paddy_app.models.validate_gst])),
                ('address', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddy_app.admintable')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_status', models.IntegerField()),
                ('overall_amount', models.BigIntegerField()),
                ('paid_amount', models.BigIntegerField(blank=True, null=True)),
                ('product_category_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('GST', models.CharField(blank=True, max_length=50, null=True)),
                ('lorry_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.IntegerField()),
                ('driver_ph_no', models.BigIntegerField()),
                ('order_date', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddy_app.admintable')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddy_app.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=255)),
                ('proof_link', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddy_app.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('subscription_status', models.IntegerField(default=0)),
                ('payment_amount', models.BigIntegerField(default=0)),
                ('subscription_type', models.CharField(max_length=255)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('additional_users', models.IntegerField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paddy_app.admintable')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paddy_app.customertable')),
            ],
        ),
    ]
