# Generated by Django 5.1.4 on 2025-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0002_rename_id_admintable_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='customer_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
