# Generated by Django 5.2 on 2025-04-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0003_alter_customertable_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
