# Generated by Django 5.1.4 on 2025-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0006_alter_admintable_email_alter_customertable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
