# Generated by Django 5.1.4 on 2025-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0007_orders_price_per_unit_alter_admintable_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
