# Generated by Django 5.1.4 on 2025-04-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0010_alter_admintable_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price_per_unit',
        ),
        migrations.AlterField(
            model_name='admintable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customertable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
