# Generated by Django 5.1.4 on 2025-04-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0011_remove_orders_price_per_unit_alter_admintable_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price_per_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
