# Generated by Django 5.1.4 on 2025-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0012_orders_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paid_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
