# Generated by Django 5.1.4 on 2025-04-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0013_alter_orders_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
