# Generated by Django 5.2 on 2025-04-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0015_subscription_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='subscription',
            name='Subscription_status',
            field=models.IntegerField(default=0),
        ),
    ]
