# Generated by Django 5.1.7 on 2025-04-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0015_subscription_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='phone_number',
        ),
    ]
