# Generated by Django 5.2 on 2025-04-08 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0016_remove_subscription_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscription_status',
            new_name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paddy_app.admintable'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paddy_app.customertable'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='additional_users',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
