# Generated by Django 5.2 on 2025-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0017_rename_subscription_status_subscription_subscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='additional_users',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
