# Generated by Django 5.2 on 2025-04-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddy_app', '0018_alter_subscription_additional_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_status',
        ),
    ]
